### ISSUE TITLE
How to create a folder in texts window?

### ISSUE THREAD

**Issue by MiroslavShard** [V0odo0/KNOT-Localization#4]
Hello! How can I create a folder to sort the keys? I can’t find the appropriate button, and it’s not described in the documentation. Screenshot taken from your video about OpenAI.

![image](https://github.com/V0odo0/KNOT-Localization/assets/50916259/cf5d2488-bcfb-488c-95f9-f48068b5952a)

**Comment by V0odo0** [comment]
In order to keep traditional key-value data structure there is no such entity as folder or directory. UI folder you see here is just visualization of UI.Exit and other keys where dot symbol is used as delimiter. 

You can disable this list view behaviour by clicking three dots symbol is upper-right corner of database window.
